### ISSUE TITLE
[BUG]: Missing ',' causes CI test to report an error

### ISSUE THREAD

**Issue by Max-918** [openbmc/phosphor-led-manager#12]
[problem 1]:  In /test/config/led-group-config-malformed.json   line 4 -> Missing a comma after `"group": "bmc_booted"` .
[problem 2]:  After problem 1 is solved, another problem appears:
![image](https://user-images.githubusercontent.com/55472156/223313620-8f2ff70e-8f52-46a7-b10f-01c0f52e152a.png)

**Comment by lxwinspur** [comment]
@Max-918 
Note: This is not a bug, This is a malformed json file intentionally used for testing, This is the expected test result.

**Comment by Max-918** [comment]
> @Max-918 Note: This is not a bug, This is a malformed json file intentionally used for testing, This is the expected test result.

Thank you very much for your reply! Can you tell me the reason for this design? What should I do if I want to pass the CI test of this package?

**Comment by Max-918** [comment]
> @Max-918 Note: This is not a bug, This is a malformed json file intentionally used for testing, This is the expected test result.

@lxwinspur 
Thank you very much for your reply! Can you tell me the reason for this design? What should I do if I want to pass the CI test of this package?

**Comment by lxwinspur** [comment]
I am not following, The current ledmanager can pass CI. I don't understand why you said that CI will report an error?
