### ISSUE TITLE
Use variables from Physical LED than the ones in Group Manager

### ISSUE THREAD

**Issue by vishwabmc** [openbmc/phosphor-led-manager#5]
LED Group manager and Physical LED manager have Blink / On / Off in their own repositories and it kind of not maintainable so need to use the definitions that are in Physical LED inside the Group Manager.

Example code that is of concern : 

 //       than giving one in ledlayout
    if(action == Layout::Action::On)  --> Group definition
    {
        return server::convertForMessage(server::Physical::Action::On); --> Physical definition
    }

**Comment by williamspatrick** [comment]
Don't think this is getting fixed in the near future, if it is still relevant.
